---
### Generate & upload reverse proxy (traefik) files
## the_builder_guy
- name: Local / Core / Reverse Proxy / Traefik / Generate files
  delegate_to: 127.0.0.1
  # 👴 deprecation warning > new 'include_tasks' can't delegate
  include: generate.yml
  vars:
    root_folder: './generated'

### Upload or update stack files in the_docker_peon /home folder
- name: Server / Core / Reverse Proxy / Traefik / Upload or update stack
  include_tasks: generate.yml
  vars:
    root_folder: '/home/{{ users.3.name }}'

### Http3 > Remove error
#     failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB).
#     See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details
- name: 'Http3 > Remove error related to buffer size'
  ansible.builtin.shell: sysctl -w net.core.rmem_max=2500000
...