---
utils_time__packagesToInstall: [
  # Chrony                / https://help.ubuntu.com/lts/serverguide/NTP.html
  'chrony',
  # Old time sync         / https://fr.wikipedia.org/wiki/Network_Time_Protocol
  # 'ntp',
  # Time zone data        / https://launchpad.net/ubuntu/+source/tzdata
  'tzdata',
]

### Time related vars
# https://github.com/fabiocorneti/ansible-clock

# If set, the hardware clock will be set to the current system time if the timezone is changed; valid values are utc or localtime. Defaults to null.
#   https://askubuntu.com/questions/175452/hwclock-not-in-sync-with-system-clock

utils_time__clock_hwclock_sync: 'localtime'

# Find the most appropriate server / https://www.pool.ntp.org/zone/@
utils_time__clock_ntpd_servers:
  - 0.europe.pool.ntp.org
  - 1.europe.pool.ntp.org
  - 2.europe.pool.ntp.org
  - 3.europe.pool.ntp.org

utils_time__clock_ntpd_fallback_servers:
  - 0.pool.ntp.org
  - ntp.ubuntu.com
  - 0.arch.pool.ntp.org

# Timezone configuration
# > timedatectl list-timezones
utils_time__clock_timezone: 'Europe/Paris'
utils_time__clock_tz_dir: '/usr/share/zoneinfo/'

# Old ntp vars
# utils_time__clock_ntpd_service: 'ntp'
...