---
# One shot synchronization
- name: Chrony one-shot sync
  command: 'chronyd -q'

# Prevent hardware desync by using localtime
- name: Sync hardware clock
  command: 'hwclock --systohc --{{ utils_time__clock_hwclock_sync }}'
  when: utils_time__clock_hwclock_sync == 'utc' or utils_time__clock_hwclock_sync == 'localtime'

- name: Restart chrony
  systemd:
    name: chrony.service
    state: restarted

# Shut down chrony
# - name: Restart timesyncd service
#   systemd:
#     enabled: yes
#     name: systemd-timesyncd.service
#     state: restarted

# Old / Ntp configuration
# - name: Restart ntpd
#   service:
#     name: {{ utils_time__clock_ntpd_service }}
#     state: restarted
...