---
### Stop {{ constants.TECHNOLOGY }} stack properly, as ansible auto reload it
## the_docker_guy

## This role must be run through a specific generated playbook.
## cf. ansible/10-forge-a-nginx.yml for use case and example.
## cf. ansible/20-forge-a-wordpress.yml for use case and example.

## Variables will be populated through the related playbook
##  see generated example: ansible/100---hello--masamune--fr---nginx-stack--stop--generated.yml

- name: "Stop {{ constants.TECHNOLOGY }} stack '{{ project.type }}---{{ project.dashed_domain }}'"
  docker_stack:
    name: '{{ project.type }}---{{ project.dashed_domain }}'
    state: absent
    #   register: my_stack_status
    
    # - debug:
    #     msg: '{{ my_stack_status }}'

- name: Wait for containers shutdown, 5 seconds
  delegate_to: 127.0.0.1
  wait_for:
    timeout: 5
...