---
### Add SSH key for user
# https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
- name: 'Set SSH key taken from file, for {{ item.name }}'
  authorized_key:
    # Need to be generated BEFORE, and added to local SSH agent
    key: "{{ lookup('file', '~/.ssh/{{ item.name }}-ssh-key-ed25519.pub') }}"
    state: present
    user: '{{ item.name }}'
  notify: ssh restart
  when:
    - users is defined

# # Vérifier la configuration, PubkeyAuthentication doit être true (par défaut)
# #   https://www.ssh.com/ssh/sshd_config
# > sudo nano /etc/ssh/sshd_config

# # Vérifier l'ajout de la clé (par défaut dans le dossier de l'utilisateur courant)
# > nano ~/.ssh/authorized_keys
# # En tant que root
# > sudo nano home/THE_USER/.ssh/authorized_keys

# # Debug avancé : vérifier les logs de connexion si toujours ko
# # En tant que root
# > sudo nano /var/log/auth.log
...