---
### Allow to use docker to user, only when specified
#   https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
- name: 'Append {{ item.name }} to the docker group : {{ item.dockerManagement }}'
  notify: Activate the changes to groups
  user:
    name: '{{ item.name }}'
    groups: docker
    append: yes
  when:
    - users is defined
    - item.dockerManagement|default(false)|bool == true
...