---
### Users
- name: Generate SSH keys locally if needed
  include: generate-ssh-key.yml
  loop: '{{ users }}'

- name: Create all users
  include: create.yml
  loop: '{{ users }}'

- name: Add SSH keys
  include: add-ssh-key.yml
  loop: '{{ users }}'

- name: Add sudoers rights
  include: add-sudoer.yml
  loop: '{{ users }}'

- name: Add CRON rights
  include: allow-cron.yml
  loop: '{{ users }}'

# https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
- name: Create docker group
  group:
      name: docker
      state: present
  when: docker.createDockerGroup|bool == true

# Usually you need to reconnect for the changes to take place, or use newgrp docker
# But in this playbook the docker guy won't work until the third playbook, which forces reconnexion
- name: Add docker rights
  include: allow-docker.yml
  loop: '{{ users }}'
  when: docker.createDockerGroup|bool == true

- name: Generate a file with manual commands for convenience
  include: generate-users-manual-commands.yml
  loop: '{{ users }}'
...