---
### Users
- name: Generate SSH keys locally
  include: generate-ssh-key.yml
  loop: '{{ users }}'

# Check if local SSH key is defined
#   No longer needed as they will be generated if needed
# https://stackoverflow.com/a/60202871/12026487
# - name: 'Check for local SSH key at ~/.ssh/{{ item.name }}-ssh-key-ed25519.pub, else skipping user creation !'
#   local_action: stat path='~/.ssh/{{ item.name }}-ssh-key-ed25519.pub'
#   loop: '{{ users }}'

- name: Create all users
  include: create.yml
  loop: '{{ users }}'

- name: Add SSH keys
  include: add-ssh-key.yml
  loop: '{{ users }}'

- name: Add sudoers rights
  include: add-sudoer.yml
  loop: '{{ users }}'

- name: Add CRON rights
  include: allow-cron.yml
  loop: '{{ users }}'

- name: Generate a file with manual commands for convenience
  include: generate-users-manual-commands.yml
  loop: '{{ users }}'
...