---
### Users
- name: Generate SSH keys locally if needed
  include: generate-ssh-key.yml
  loop: '{{ users }}'

- name: Create all users
  include: create.yml
  loop: '{{ users }}'

- name: Add SSH keys
  include: add-ssh-key.yml
  loop: '{{ users }}'

- name: Add sudoers rights
  include: add-sudoer.yml
  loop: '{{ users }}'

- name: Add CRON rights
  include: allow-cron.yml
  loop: '{{ users }}'

- name: Generate a file with manual commands for convenience
  include: generate-users-manual-commands.yml
  loop: '{{ users }}'
...