---
### Prevent access to /home/da_user directory from other users, only when specified
#     https://help.ubuntu.com/lts/serverguide/serverguide.pdf#page=188&zoom=100,72,96
- name: 'Prevent access to /home/{{ item.name }} from other users : {{ item.preventHomeAccess }}'
  file:
    path: '/home/{{ item.name }}'
    state: directory
    mode: '0750'
  when:
    - users is defined
    - item.preventHomeAccess|default(true)|bool == true
...