---
### Setup chroot prison
#     https://github.com/youpiwaza/server-related-tutorials/tree/master/04-user-restrict-and-sftp

- name: Create dedicated sftp user group
  group:
    name: chroot-prison-sftp-users
    state: present

- name: Create chroot prison main folder
  file:
    group: root
    owner: root
    path: '/home/{{ users.3.name }}/clients/_websites_files_sftp_access_chroot_prison/'
    state: directory

- name: Create chroot prison main folder README.md
  template:
    dest: '/home/{{ users.3.name }}/clients/_websites_files_sftp_access_chroot_prison/README.md'
    src: chroot-prison-root-README.md.j2
...