---
## the_builder_guy
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/stack/'
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history/stack/'

- name: Generate wordpress.yml'
  template:
    dest: '{{ item }}'
    src: templates/wordpress.yml.j2
  loop:
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/stack/{{ project.dashed_domain }}---wordpress--generated.yml'
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history/stack/{{ project.dashed_domain }}---wordpress--generated-{{ currentDateTime }}.yml'
...