---
### Locally generate README.md file containing wordpress infos
- name: Generate ids-README.md file containing wordpress ids & infos
  template:
    dest: '{{ item }}'
    src: templates/ids-README.md.j2
  loop:
    - './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/{{ project.dashed_domain }}---ids-README-generated.md'
    - './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history/{{ project.dashed_domain }}---ids-README-generated-{{ currentDateTime }}.md'

- debug:
    msg: 
      - "A file containing all website infos '/generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/{{ project.dashed_domain }}---ids-README-generated.md' have been generated in the /generated/ folder of this project :)"
      - "Consider storing it in a safe place (private repo) and then delete the local file"
...