---
### WordPress project generation: Variables + var files + .yml file
## builder_guy

## This role must be run through a specific playbook.
## cf. ansible/20-forge-a-wordpress-playbook.yml for use case and example.

- name: Warning, this role needs a file providing variables
  debug:
    msg: "\n\nBEFORE RUNNING THIS ROLE !
          \n\nThis role must be run through a specific playbook generated through ansible/20-forge-a-wordpress-playbook.yml
          \n\nIt also needs a specific file containing variables\n\n"

- name: 'Read the warning message ^'
  wait_for:
    timeout: 5

- name: Local / Test / Web / Wordpress / Generate ids in a local README.md file
  delegate_to: 127.0.0.1
  include: generate-ids-readme.yml

### Generate & upload web server wordpress files
## the_builder_guy
- name: Local / Test / Web / Wordpress / Generate files
  delegate_to: 127.0.0.1
  include: generate-yml.yml
  vars:
    root_folder: './generated'

### Upload or update stack files in the_docker_peon /home folder
- name: Server / Test / Web / Wordpress / Upload or update stack
  include: generate-yml.yml
  vars:
    root_folder: '/home/{{ users.3.name }}'
...