---
### Generate & upload web server nginx files
## the_builder_guy
- name: Local / Test / Web / Nginx / Generate files
  delegate_to: 127.0.0.1
  include: generate.yml
  vars:
    root_folder: './generated'

### Upload or update stack files in the_docker_peon /home folder
- name: Server / Test / Web / Nginx / Upload or update stack
  include: generate.yml
  vars:
    root_folder: '/home/{{ users.3.name }}'
...