---
### WordPress project generation related vars

database:
  image: 'bitnami/mariadb:10.3'
  MARIADB_DATABASE: 'bitnami_wordpress_drdS87QVpvADFw5W'
  MARIADB_PASSWORD: 'G6Sn3VaLqf2DDL9W'
  MARIADB_USER: 'yAKqwcWYAr9kzLdn'
  MARIADB_ROOT_PASSWORD: 'F9pXgdTAwcWSxH4WnZYex3pLJmR947VZ'
  MARIADB_ROOT_USER: 'root_F5g8H7F'

project:
  client_name: 'masamune'
  # Docker recommanded notation: extension.site.subdomain.SOME-LABEL
  #   https://docs.docker.com/config/labels-custom-metadata/#key-format-recommendations
  labels_prefix: 'fr.masamune.test-wordpress'
  maintainer: 'masamune.code@gmail.com'
  name: 'test wordpress'
  type: 'test'

traefik:
  # Ensure DNS are set accordingly to point towards host IP
  # This will point towards 'https://test-wordpress.masamune.fr/'
  public_uri: 'test-wordpress.masamune.fr'
  # For router & middleware names generation
  # subDomain_domain_ext__stacktype
  uid: 'testWordpress_masamune_fr__wordpress'

wordpress:
  image: 'bitnami/wordpress:5'
  WORDPRESS_TABLE_PREFIX: 'wp_PL9ZFfYp_'
  WORDPRESS_BLOG_NAME: "Sponge Bob's blog"
  WORDPRESS_EMAIL: 'masamune.code@gmail.com'
  WORDPRESS_FIRST_NAME: 'Bob'
  WORDPRESS_LAST_NAME: 'Sponge'
  # 50 chars length / NO SPECIAL CHARS, tends to not match when container is up
  WORDPRESS_USERNAME: 'ndj4E2rDbVeRkEHHcu9X7me3asqTNFmzwjKAhU9LbqpMb8Wbcf'
  # 50 chars length / Wordpress recommandations : ! ? % ^ & ) / No no $ ' "
  WORDPRESS_PASSWORD: 'ndj4E2r!bVeRkE?Hcu8%7me3as^TNFmzwjKAh)U9Lbqp&b8Wbcf'
...