---
### WordPress ansible playbook generation: .yml file
## builder_guy

## This role must be run through a specific playbook.
## cf. ansible/20-forge-a-wordpress.yml for use case and example.

- name: Warning, without manual action this role will run an example
  debug:
    msg: 
      - "BEFORE RUNNING THIS ROLE !"
      - "Duplicate 'ansible/roles/stack-web-wordpress--generate-playbooks/vars/template.yml' to a proper location"
      - "for example : 'ansible/roles/stack-web-wordpress--generate-playbooks/vars/TYPE/CLIENT/DASHED-DOMAIN/DASHED-DOMAIN---vars_secret.yml'"
      - "and modify the '20-forge-a-wordpress.yml' playbook accordingly in vars : set the path to the new file."

- name: 'Read the warning message ^'
  wait_for:
    timeout: 5

# Create generated/ local directory
- name: Create directory './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history'
  delegate_to: 127.0.0.1
  file:
    path: './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history'
    state: directory



## Generate all playbooks, customized using the duplicated project vars files
- name: Generate WordPress start playbook
  delegate_to: 127.0.0.1
  template:
    dest: '{{ item }}'
    src: wordpress-playbook-start.yml.j2
  loop:
    - './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/200---{{ project.dashed_domain }}---wordpress-stack--start--generated.yml'
    - './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history/200---{{ project.dashed_domain }}---wordpress-stack--start--generated-{{ currentDateTime }}.yml'
    # Convenience : duplicate to root
    - './200---{{ project.dashed_domain }}---wordpress-stack--start--generated.yml'



- name: Everything went fine :)
  debug:
    msg:
      - "You can now run the newly generated playbook, it will use the same file for your project's vars."
      - "It will generate the stack .yml files, then upload/update them, and finally deploy the stack !"
      - "Here's the command :"
      - ""
      - "ansible-playbook -i hostsWithCustomSSHPort 200---{{ project.dashed_domain }}---forge-wordpress-stack--generated.yml"
...