---
### Nginx ansible playbook generation: .yml file
## builder_guy

## This role must be run through a specific playbook.
## cf. ansible/10-forge-a-nginx-playbook.yml for use case and example.

- name: Warning, without manual action this role will run an example
  debug:
    msg: "\n\nBEFORE RUNNING THIS ROLE !
          \n\nDuplicate 'ansible/roles/stack-web-nginx--generate-playbook/vars/template.yml' to a proper location, ex. 'ansible/roles/stack-web-nginx--generate-playbook/vars/TYPE/CLIENT/DASHED-DOMAIN/DASHED-DOMAIN---vars_secret.yml'
          \n\nand modify the '10-forge-a-nginx-playbook.yml' playbook accordingly.\n\n"

- name: 'Read the warning message ^'
  wait_for:
    timeout: 5

- name: Generate '/100---{{ project.dashed_domain }}---forge-nginx-stack--generated.yml'
  delegate_to: 127.0.0.1
  template:
    dest: './100---{{ project.dashed_domain }}---forge-nginx-stack--generated.yml'
    src: nginx-playbook.yml.j2

- name: Create directory './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/playbooks/'
  delegate_to: 127.0.0.1
  file:
    path: './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/playbooks/'
    state: directory

- name: History / Generate './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/playbooks/100---{{ project.dashed_domain }}---forge-nginx-stack--generated-{{ currentDateTime }}.yml'
  delegate_to: 127.0.0.1
  template:
    dest: './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/playbooks/100---{{ project.dashed_domain }}---forge-nginx-stack--generated-{{ currentDateTime }}.yml'
    src: nginx-playbook.yml.j2
...