---
packagesToInstall: [
  # Firewall              / https://doc.ubuntu-fr.org/iptables    / Required for Oh my ZSH
  'iptables'
]

iptables_restart_dependent_services:
  - name: 'docker'
    path: '/etc/systemd/system/'
...