---
### ZSH configuration, used only for root
# Note: If this file is modified, update both utils-zshrc.yml and utils-zshrc-for-root.yml

# Install for each user
- name: 'Cloning oh-my-zsh for root'
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: '/root/.oh-my-zsh'

## Create the .zshrc file, only if it doesn't exist already, to prevent local config override
# If config is already here, new theme won't be applied
- name: "Check for root's .zshrc"
  stat:
    path: '/root/.zshrc'
  register: is_zshrc

# Note: Might need to > 'source .zshrc' if still logged in to apply changes
- name: 'Create .zshrc for root if needed'
  template:
    dest: '/root/.zshrc'
    src: templates/zshrc.j2
  when: is_zshrc.stat.exists|default(false)|bool == false

## Set user's terminal to zsh, AFTER INSTALLATION
# else it prevents SSH login !
- name: 'Change default terminal for root'
  user:
    name: 'root'
    shell: /usr/bin/zsh
...