---
### ZSH configuration, used for each user
# Note: If this file is modified, update both utils-zshrc.yml and utils-zshrc-for-root.yml

# Install for each user
- name: 'Cloning oh-my-zsh for {{ item.name }}'
  git:
    force: yes
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: '/home/{{ item.name }}/.oh-my-zsh'

## Create the .zshrc file, only if it doesn't exist already, to prevent local config override
# If config is already here, new theme won't be applied
- name: "Check for {{ item.name }}'s .zshrc"
  stat:
    path: '/home/{{ item.name }}/.zshrc'
  register: is_zshrc

# Note: Might need to > 'source .zshrc' if still logged in to apply changes
- name: 'Create .zshrc for {{ item.name }} if needed'
  template:
    dest: '/home/{{ item.name }}/.zshrc'
    src: templates/zshrc.j2
  when: is_zshrc.stat.exists|default(false)|bool == false

## Set user's terminal to zsh, AFTER INSTALLATION
# else it prevents SSH login !
- name: 'Change default terminal to zsh for {{ item.name }}'
  user:
    name: '{{ item.name }}'
    shell: /usr/bin/zsh
...