---
### WordPress project generation: Variables + var files + .yml file
## This role contains default vars, that can (and SHOULD) be overriden in playbook.
## cf. ansible/20-forge-a-wordpress-stack.yml use case, that uses random string generation

- name: Custom website variables warning
  debug:
    msg: "\n\nBEFORE RUNNING THIS ROLE !
          \n\nDuplicate 'ansible/roles/stack-web-wordpress--generate/vars/template.yml' to a proper location, ex. 'ansible/roles/stack-web-wordpress--generate/vars/TYPE/CLIENT/DASHED-DOMAIN/main_secret.yml'
          \n\nand modify/duplicate the '20-forge-a-wordpress-stack.yml' playbook accordingly.\n\n"

- name: 'Read the warning message ^'
  wait_for:
    timeout: 5

- name: Local / Test / Web / Wordpress / Generate ids in a local README.md file
  delegate_to: 127.0.0.1
  include: generate-ids-readme.yml

### Generate & upload web server wordpress files
## the_builder_guy
- name: Local / Test / Web / Wordpress / Generate files
  delegate_to: 127.0.0.1
  include: generate-wordpress-stack-file.yml
  vars:
    root_folder: './generated'

### Upload or update stack files in the_docker_peon /home folder
- name: Server / Test / Web / Wordpress / Upload or update stack
  include: generate-wordpress-stack-file.yml
  vars:
    root_folder: '/home/{{ users.3.name }}'
...