---
## Stop Nginx stack, as ansible auto reload it
## the_docker_guy
# > ansible-playbook -i hostsWithCustomSSHPort 100---hello--masamune--fr---nginx-stack--stop--generated.yml

# You'll need the_docker_guy to have it's ssh key added to the local agent, cf. the_docker_guy generated documentation

## the_docker_guy
- name: '{{ users.2.name }} / Stop Nginx stack'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml
  - roles/stack-web-nginx--generate-playbooks/vars/tests/masamune/hello--masamune--fr/hello--masamune--fr---vars.yml

  roles:
    - stack-web-common--stop
...