---
### Configure the terminal, with zsh + oh-my-zsh + powerlevel10k
#   ZSH                 / https://www.zsh.org/
#   Oh My ZSH           / https://ohmyz.sh/
#   Powerlevel10k theme / https://github.com/romkatv/powerlevel10k#oh-my-zsh

# Requires following packages : curl, fonts-powerline, git
# Note: Zsh should be set as the default shell / https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH
# This is defined during user creation

# Oh my zsh global installation / https://stackoverflow.com/questions/31624649/how-can-i-get-a-secure-system-wide-oh-my-zsh-configuration

# Only if zsh is installed
#   https://docs.ansible.com/ansible/latest/modules/package_facts_module.html
# TODO: KO / Requirements > For Debian-based systems python-apt package must be installed on targeted hosts
# when: "'zsh' in ansible_facts.packages"

# Include main.yaml ( {{ users }} ) into the 'loaded_users' variable (2.2).
#   https://docs.ansible.com/ansible/latest/modules/include_vars_module.html
- name: Configure terminal for all users
# - name: Include users list, from users roles
  include_vars:
    file: ../../users/vars/main.yml
    name: loaded_users

## Merge remote_user with created users, to allow loop refacto
#   https://blog.crisp.se/2016/10/20/maxwenzin/how-to-append-to-lists-in-ansible
# Create a single element list
- name: Setup a list containing remote_user, to be merged into users
  set_fact:
    list_of_remote_user_only:
      - name: '{{ my_remote_user }}'

- name: Merge the two lists
  set_fact:
    # Users list is in users var
    lists_merged: "{{ loaded_users.users + list_of_remote_user_only }}"

## Loop for every user, including remote_user
- name: Install and setup zsh for all users
  include: utils-zshrc.yml
  loop: '{{ lists_merged }}'

# Default config / https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template
# TODO: Fix root tweak (root's $HOME directory isn't the same as others users)
# Others have /home/$USERNAME
# root has /root
- name: Creating zshrc default configuration for all users
  template:
    dest: /etc/zsh/zshrc
    src: templates/zshrc-default.j2
...