---
# https://docs.ansible.com/ansible/latest/scenario_guides/guide_docker.html
bothHostsPipPackagesToInstall: [
  'docker'
]

# It reduces server performances and isn't mandatory if you uses services
#   https://docs.docker.com/config/containers/resource_constraints/
#     https://docs.docker.com/install/linux/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
#   https://docs.docker.com/config/containers/resource_constraints/#understand-the-risks-of-running-out-of-memory
#   > Consider converting your container to a service, and using service-level constraints
#   > and node labels to ensure that the application runs only on hosts with enough memory
# Ansible can manage it
#   https://docs.ansible.com/ansible/latest/modules/docker_swarm_service_module.html#parameter-reservations
enableDockerSwapLimitSupport: no

# https://docs.ansible.com/ansible/latest/modules/pip_module.html > Requirements
localHostPackagesToInstall: [
  'python3-pip',
  'python3-setuptools',
  'virtualenv'
]

nginxTestImage: 'nginx:1.16.1-alpine'

# https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-engine---community-1
remoteHostDockerPackagesToInstall: [
  'docker-ce',
  'docker-ce-cli',
  'containerd.io'
]

# https://docs.docker.com/install/linux/docker-ce/ubuntu/#uninstall-old-versions
remoteHostOldPackagesToUninstall: [
  'docker',
  'docker-engine',
  'docker.io',
  'containerd',
  'runc'
]

# https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository
# https://docs.ansible.com/ansible/latest/modules/pip_module.html > Requirements
remoteHostPackagesToInstall: [
  'apt-transport-https',
  'ca-certificates',
  'curl',
  'gnupg-agent',
  'python3-pip',
  'python3-setuptools',
  'software-properties-common',
  'virtualenv'
]
...