---
### Nginx stack uninstall: Remove volumes, configs, etc.
## docker_guy

## This role must be run through a specific playbook.
## cf. ansible/10-forge-a-nginx-stack.yml for use case and example.

## This role is meant to be run AFTER the 'stack-web-common--stop' role which will stop the containers.

### Volumes management
## Logs

## TODO: Run the backup role before removing named volume

## Note: No container state test yet. I've kept it simple with a time delay.
## LATER: Clean: Wait for container actually stopped
## SO bash workaround : https://github.com/moby/moby/issues/30942

# - name: Wait for containers shutdown
#   wait_for:
#     docker_stack:
#       name: '{{ project.type }}---{{ project.dashed_domain }}'
#       state: absent

- debug:
    msg:
      - "Warning, this role will remove the named volumes associated to the project '{{ project.dashed_domain }}' from client '{{ project.client_name }}'"
      # - "TODO: Add a final backup before removing"

- name: Wait for containers shutdown, 5 seconds
  wait_for:
    timeout: 5

# docker volume rm test---hello--masamune--fr---nginx--logs

- name: "Remove named volume for Nginx logs '{{ project.type }}---{{ project.dashed_domain }}---nginx--logs'"
  docker_volume:
    name: '{{ project.type }}---{{ project.dashed_domain }}---nginx--logs'
    state: absent
...