---
### Update system and packages, then lint
- name: Update system
  # include: update-os.yml
  include_tasks: update-os.yml

- name: Update packages
  # include: update-packages.yml
  include_tasks: update-packages.yml

- name: Clean dependancies et reboot if needed
  # include: clean-packages.yml
  include_tasks: clean-packages.yml

- name: User feedback
  # include: confirmation.yml
  include_tasks: confirmation.yml
...