---
# https://coderwall.com/p/0nckqg/ansible-reboot-ubuntu-if-needed, cf. comments
- name: Reboot system if required
  command: shutdown -r now 'Rebooting to complete system upgrade'
    removes=/var/run/reboot-required
...