---
### Update OS and packages, then reboot if needed
#   https://help.ubuntu.com/lts/serverguide/installing-upgrading.html
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure update-manager-core is installed.
  apt:
    name: update-manager-core
    state: present

- name: Reboot system if required
  include: reboot-if-needed.yml

# Warn user
- debug:
    msg: 'Might crash ansible if a major upgrade is made. Then just wait for it and restart the ansible script :)'

# Use -f DistUpgradeViewNonInteractive to force yes to all questions, removing the need for user inputs
#   https://www.linuxnix.com/ubuntu-linuxhow-to-do-unattended-os-release-upgrade/
# Use -d to force check the latest LTS / Here Ubuntu 20.04 LTS released on 23rd April 2020
#   https://www.linuxtechi.com/upgrade-ubuntu-18-04-lts-to-ubuntu-20-04-lts/
- name: Run do-release-upgrade non-interactively.
  command: do-release-upgrade -df DistUpgradeViewNonInteractive
  register: result
  # Later: Clean
  failed_when: "result.stderr != ''"

- debug:
    msg: "Ubuntu upgrade message : {{ result.stdout }}"

- name: Reboot system if required
  include: reboot-if-needed.yml
...