---
### Update OS and packages, then reboot if needed
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure update-manager-core is installed.
  apt:
    name: update-manager-core
    state: present

- name: Reboot system if required
  include: reboot-if-needed.yml

# TODO: Fix
# https://www.linuxnix.com/ubuntu-linuxhow-to-do-unattended-os-release-upgrade/
# - name: Run do-release-upgrade non-interactively.
#   command: do-release-upgrade -f DistUpgradeViewNonInteractive
#   register: result
  # failed_when: '"No new release found" not in result.stdout'
...