---
### Docker maintenance
## Remove dangling containers, networks, volumes, and downloaded images (Docker Bench Security > avoid image sprawl)

# https://docs.ansible.com/ansible/latest/modules/docker_prune_module.html
- name: Prune everything (including orphan networks, orphans volumes, non-dangling images & builder cache)
  docker_prune:
    containers: yes
    images: yes
    images_filters:
      dangling: false
    networks: yes
    volumes: yes
    builder_cache: yes
...