---
### Change serveur default SSH port
## File edition
# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html

- name: Change serveur default SSH port
  lineinfile:
    insertafter: '^#Port '
    # Replace line with
    line: 'Port {{ custom_ssh_port }}'
    # File to modify
    path: '/etc/ssh/sshd_config'
    # Attention à l'échappement
    regexp: '^Port'
  # Restart ssh service
  notify: restart ssh
...