---
### Install core stack : reverse proxy (traefik)
## the_builder_guy

# Install project compose file in the_docker_peon /home folder
- name: 'Create traefik directory /home/{{ users.3.name }}/core/reverse-proxy/traefik/'
  file:
    path: '/home/{{ users.3.name }}/core/reverse-proxy/traefik/'
    state: directory

- name: Add traefik compose file from template
  template:
    dest: '/home/{{ users.3.name }}/core/reverse-proxy/traefik/traefik.yml'
    src: templates/traefik.j2
...