---
### Remove a sftp user
# Use with playbook:
# - 95-remove-sftp-user.yml
- name: Remove README file with user instructions to setup sftp connection
  file:
    path: './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/tutorial-setup-sftp/_{{ userToRemove.name }}-tutorial-setup-sftp--generated.md'
    state: absent
  # On the local machine
  delegate_to: 127.0.0.1

- name: "Has user's local SSH keys have been deleted yet ?"
  stat: 'path=~/.ssh/{{ userToRemove.name }}-ssh-key-ed25519.pub'
  register: isUserLocalSshKeyPresent
  # On the local machine
  delegate_to: 127.0.0.1

## Remove from host before removing it from local, as you need the .pub file
- name: 'Remove SSH key on host, for {{ userToRemove.name }}'
  authorized_key:
    # Need to be generated BEFORE, and added to local SSH agent
    key: "{{ lookup('file', '~/.ssh/{{ userToRemove.name }}-ssh-key-ed25519.pub') }}"
    state: absent
    user: '{{ userToRemove.name }}'
  notify: Restart ssh service
  when: isUserLocalSshKeyPresent.stat.exists

- name: 'Remove SSH local keys / ~/.ssh/{{ userToRemove.name }}-ssh-key-ed25519{{ item }}'
  file:
    path: '~/.ssh/{{ userToRemove.name }}-ssh-key-ed25519{{ item }}'
    state: absent
  delegate_to: 127.0.0.1
  with_items:
    - ''
    - '.ppk'
    - '.pub'
    # Manually generated for FTP client (key conversion ed25519 to rsa or somethingss)
    - '-pour-client-ftp.ppk'

- name: 'Remove SSH local passphrase'
  file:
    path: './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/vars-files/{{ project.client_name }}---{{ project.dashed_domain }}---SFTP_PASSPHRASE-generated.txt'
    state: absent
  delegate_to: 127.0.0.1

- name: "Delete {{ userToRemove.name }}'s chroot prison /home folder"
  file:
    path: '/home/{{ users.3.name }}/clients/_websites_files_sftp_access_chroot_prison/{{ userToRemove.name }}/'
    state: absent

- name: 'Remove ubuntu user "{{ userToRemove.name }}"'
  user:
    name: '{{ userToRemove.name }}'
    state: absent
...