---
### Generate wordpress-stack.yml file

- name: Local / Debug / Generate wordpress-stack--generated.yml file
  template:
    dest: './tmp/{{ project.type }}--{{ project.client_name }}--{{ project.dashed_domain }}--wordpress-stack--generated.yml'
    src: templates/wordpress-stack.yml.j2
  delegate_to: 127.0.0.1

- debug:
    msg: "\n\nA stack file '{{ project.type }}--{{ project.client_name }}--{{ project.dashed_domain }}--wordpress-stack--generated.yml' have been generated at the root of this project :)\n"

- name: 'Create type/client/project/ directory for wordpress : /home/{{ users.3.name }}/{{ project.type }}/{{ project.client_name }}/{{ project.dashed_domain }}/'
  file:
    path: '/home/{{ users.3.name }}/{{ project.type }}/{{ project.client_name }}/{{ project.dashed_domain }}/'
    state: directory

- name: Generate wordpress-stack--generated.yml file
  template:
    dest: '/home/{{ users.3.name }}/{{ project.type }}/{{ project.client_name }}/{{ project.dashed_domain }}/wordpress-stack--generated.yml'
    src: templates/wordpress-stack.yml.j2

- debug:
    msg: "\n\nThe stack file '/home/{{ users.3.name }}/{{ project.type }}/{{ project.client_name }}/{{ project.dashed_domain }}/wordpress-stack--generated.yml' have been generated :)\n"
...