---
# ### Template vars file if you want to override some variables
# ## Global vars

# # If you want to change the default SSH port
# #   Also used for iptables firewall rules
# global__custom_ssh_port: 6969

# # Email used for notifications
# global__admin_email: YOUR_EMAIL

# # Default root user to connect to your server, usually root
# # global__remote_user: YOUR_REMOTE_USER
# global__remote_user: root

# # Ip adresse of your server
# # Must also be set in /ansible/hosts & hostsWithCustomSSHPort
# global__remote_host: 169.169.169.169

# # SSH pass phrase for ssh key authentication (no password)
# # Root will be mostly used only to set up other users
# # https://passwordsgenerator.net/ / lower and UPPERCASE, numbers and special chars
# global__remote_host_ssh_passphrase: whatever

# # Alpine image to test all the docker stuff on
# global__alpineTestImage: 'alpine:3.11.5'

# # Nginx image to test all the docker stuff on
# global__nginxTestImage: 'nginx:1.16.1-alpine'


# ## Docker compose installation
# # pip packages to install both locally & on remote host
# docker_compose_installation__bothHostsPipPackagesToInstall: [
#   'docker-compose',
#   'PyYAML'
# ]

# docker_compose_installation__publicRepo: 
#   name: docker-compose-example
#   uri: https://github.com/youpiwaza/docker-compose-example.git

# docker_compose_installation__publicRepoCurated: 
#   name: docker-compose-curated-example
#   uri: https://github.com/youpiwaza/docker-compose-curated-example.git


# ## Docker installation
# docker_installation__bothHostsPipPackagesToInstall: [
#   'docker'
# ]

# docker_installation__dockerBenchSecurityPackagesToInstall: [
#   'auditd'
# ]

# # Some values for /etc/docker/daemon.json
# docker_installation__dockerConfig:
#   # This example sets a soft limit of 128 open files and 32 child processes and a hard limit of 256 open files and 64 child processes on the container.
#   #   https://docs.oracle.com/en/operating-systems/oracle-linux/docker/ch04s16.html
#   default_ulimits:
#     nofile:
#       hard: 256
#       soft: 128
#     nproc:
#       hard: 64
#       soft: 32
...