---
### Test docker through a nginx container
## Pulls nginx alpine image, creates and start the container, curl host ip on port 80, then stop and removes the container

# https://hub.docker.com/_/nginx
- name: Test docker through a nginx container / Pull default nginx image
  docker_image:
    name: '{{ nginxTestImage }}'
    source: pull

- name: Warning about running container
  debug:
    msg: 'Be careful, if this playbook fails, it will not end and the container will still be running !'

- name: Don't run on docker default bridge network, create a custom one
  docker_network:
    driver: bridge
    labels:
      fr.masamune.project: 'custom bridge network'
    name: test-custom-bridge

- name: Create a nginx test container, on port 80 (other are closed by firewall)
  docker_container:
    healthcheck:
      test: 'stat /etc/nginx/nginx.conf || exit 1'
    image: '{{ nginxTestImage }}'
    labels:
      fr.masamune.project: 'Test nginx run by the_docker_guy'
    name: nginx-test
    networks:
      - name: test-custom-bridge
    ports:
      - '80:80'
    state: started
    # Authorize port 80 for test purposes # Always authorize port > 1024 only
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    volumes:
      - '/home/the_docker_peon/tests-volume/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      # - '/home/the_docker_peon/tests-volume/nginx/content:/usr/share/nginx/html:ro'
    working_dir: '/usr/share/nginx/html'

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: 'http://{{ ansible_host }}/'

- name: "Check that a page returns a status 200 and fail if the words 'Welcome to nginx!' is not in the page contents"
  uri:
    url: 'http://{{ ansible_host }}/'
    return_content: yes
  register: da_webpage
  failed_when: "'Welcome to nginx!' not in da_webpage.content"

- name: Display page content in ansible logs
  debug:
    msg: 'Affichage du contenu de la page :\n\n{{ da_webpage.content }}'

# You can comment the next 2 tasks and go check the nginx default page on your server's IP (cf. hosts) :)
- name: Remove test container
  docker_container:
    name: nginx-test
    state: absent

- name: Remove docker default bridge network
  docker_network:
    name: test-custom-bridge
    state: absent
...