---
### Change serveur default SSH port
## File edition
# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html

- name: Change serveur default SSH port
  lineinfile:
    insertafter: '^#Port '
    # Replace line with
    line: 'Port {{ global__custom_ssh_port }}'
    # File to modify
    path: '/etc/ssh/sshd_config'
    # Attention à l'échappement
    regexp: '^Port'
    # Validate sshd config file before change, # %s is mandatory for ansible but useless for this command
    validate: 'sshd -t %s'
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html
    # validate: /usr/sbin/sshd -T -f %s
  # Restart ssh service
  notify: Restart ssh service
...