---
### WordPress stack uninstall: Remove volumes, configs, etc.
## docker_guy

## This role must be run through a specific playbook.
## cf. ansible/20-forge-a-wordpress-stack.yml for use case and example.

## This role is meant to be run AFTER the 'stack-web-common--stop' role which will stop the containers.

- debug:
    msg:
      - "Warning, this role will remove the named volumes associated to the project '{{ project.dashed_domain }}' from client '{{ project.client_name }}'"
      - "If the playbook fails, wait a little longer and restart it."
      # - "TODO: Add a final backup before removing"

- name: Wait for containers shutdown, 5 seconds
  wait_for:
    timeout: 5



### Volumes management
## Database
- name: "Remove named volume for WordPress database '{{ project.type }}---{{ project.dashed_domain }}---wordpress--database'"
  docker_volume:
    name: '{{ project.type }}---{{ project.dashed_domain }}---wordpress--database'
    state: absent


## Files
- name: "Remove named volume for WordPress files '{{ project.type }}---{{ project.dashed_domain }}---wordpress--files'"
  docker_volume:
    name: '{{ project.type }}---{{ project.dashed_domain }}---wordpress--files'
    state: absent
...