---
## Time
# Prevent hardware desync by using localtime
- name: Sync hardware clock
  command: 'hwclock --systohc --{{ clock_hwclock_sync }}'
  when: clock_hwclock_sync == 'utc' or clock_hwclock_sync == 'localtime'

- name: Restart ntpd
  service:
    name: '{{ clock_ntpd_service }}'
    state: restarted
...