---
### Restore a previously backuped volume: Extract an (host) archive into a volume
## docker_guy
# > ansible-playbook -i hostsWithCustomSSHPort 200---test-wordpress--masamune--fr---wordpress-backup-restore-volume-from-host-archive.yml

# 🚨 Note 🚨 : This will replace existing files but **not erase new files**.
#        Best practice would be to create a new volume, populate it with the backup and remap the container accordingly.
#        This also allow the previous volume (..and datas) to persist.

# 🔧🚨💥 Variables must be properly filled:
# - archiveLocationOnHost : The path to the folder containing the archive to restore from (.tar file), located on host, without last slash
# - archiveName           : The archive filename to restore from (.tar file), located on host. Includes extension
# - folderToRestore       : The folder where the files are going to be restored INSIDE the volume
# - volumeName            : Identifier of the named volume to restore to a previous state

# For more details, have a look at docker-commands-template.md###Create a backup

# You'll need the_docker_guy to have it's ssh key added to the local agent, cf. the_docker_guy generated documentation

- name: 'Restore a backup archive into a specific volume: WordPress database'
  become: no
  hosts: likorneWithCustomSSHPort
  # docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars:
    ## 🔧 Edit variables here
    # cf. ansible/roles/stack-web-wordpress--generate-stack/templates/wordpress.yml.j2 > volumes > target
    # archiveLocationOnHost: '/home/{{ users.2.name }}/backups/volumes/{{ currentYear }}/{{ type || "manual-backup" }}s/{{ client }}/{{ volumeName }}'
    # archiveLocationOnHost: '/home/the-docker-guy/backups/volumes/2021/manual-backups/masamune/test-wordpress--masamune--fr/test---test-wordpress--masamune--fr---wordpress--database'
    # archiveLocationOnHost: '/home/the-docker-guy/backups/volumes/2021/tests/masamune/test-wordpress--masamune--fr/test---test-wordpress--masamune--fr---wordpress--database'
    archiveLocationOnHost: '/home/{{ users.2.name }}/backups/volumes/2021/manual-backups/masamune/test-wordpress--masamune--fr/test---test-wordpress--masamune--fr---wordpress--database'
    
    # archiveName: '{{ volumeName }}---backup---latest.tar'
    archiveName: 'test---test-wordpress--masamune--fr---wordpress--database---backup---latest.tar'
    
    folderToRestore: '/bitnami/mariadb/'
    # cf. ansible/roles/stack-web-nginx--deploy/tasks/main.yml
    volumeName: '{{ project.type }}---{{ project.dashed_domain }}---wordpress--database'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml
  # 🔧 project.vars_file_path
  - roles/stack-web-wordpress--generate-playbooks/vars/tests/masamune/test-wordpress--masamune--fr/test-wordpress--masamune--fr---vars.yml

  roles:
    - docker-volume-restore-from-host-archive



- name: 'Restore a backup archive into a specific volume: WordPress files'
  become: no
  hosts: likorneWithCustomSSHPort
  # docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars:
    ## 🔧 Edit variables here
    # cf. ansible/roles/stack-web-wordpress--generate-stack/templates/wordpress.yml.j2 > volumes > target
    # archiveLocationOnHost: '/home/{{ users.2.name }}/backups/volumes/{{ currentYear }}/{{ type || "manual-backup" }}s/{{ client }}/{{ volumeName }}'
    # archiveLocationOnHost: '/home/the-docker-guy/backups/volumes/2021/manual-backups/masamune/test-wordpress--masamune--fr/test---test-wordpress--masamune--fr------wordpress--files'
    # archiveLocationOnHost: '/home/the-docker-guy/backups/volumes/2021/tests/masamune/test-wordpress--masamune--fr/test---test-wordpress--masamune--fr------wordpress--files'
    archiveLocationOnHost: '/home/{{ users.2.name }}/backups/volumes/2021/manual-backups/masamune/test-wordpress--masamune--fr/test---test-wordpress--masamune--fr------wordpress--files'
    
    # archiveName     : '{{ volumeName }}---backup---latest.tar'
    archiveName: 'test---test-wordpress--masamune--fr------wordpress--files---backup---latest.tar'
    
    folderToRestore: '/bitnami/wordpress/'
    # cf. ansible/roles/stack-web-nginx--deploy/tasks/main.yml
    volumeName: '{{ project.type }}---{{ project.dashed_domain }}---wordpress--files'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml
  # 🔧 project.vars_file_path
  - roles/stack-web-wordpress--generate-playbooks/vars/tests/masamune/test-wordpress--masamune--fr/test-wordpress--masamune--fr---vars.yml

  roles:
    - docker-volume-restore-from-host-archive
...