---
# From /templates, will be used during containers start. Do not enforce
security_apparmor__appArmorProfilesToAdd:
  - 'docker-nginx'

# See files on host in /etc/apparmor.d/
security_apparmor__appArmorProfilesToEnforce:
  # Example
  - 'usr.sbin.chronyd'

# https://help.ubuntu.com/lts/serverguide/serverguide.pdf#page=200
security_apparmor__packagesToInstall: [
  'apparmor',
  'apparmor-profiles',
  'apparmor-utils',
  'auditd'
]
...