---
### Event based tasks ###
# Load new SSH configuration
- name: Restart ssh service
  service:
    name: ssh
    state: restarted

- name: Restart sshd service
  service:
    name: sshd
    state: restarted
...