---
### Setup a Nginx web server, displaying a 'hello world' page on a specific URI
# Example & boilerplate to start a container with security & reverse proxy
# First example is basic nginx, second with php config

### Docker required services setup
# Traefik / Reverse proxy

# Example command
# > ansible-playbook -i hostsWithCustomSSHPort 10-forge-a-nginx-stack.yml

# You'll need the_builder_guy to have it's ssh key added to the local agent, cf. the_builder_guy generated documentation
# You'll need the_docker_guy  to have it's ssh key added to the local agent, cf. the_docker_guy  generated documentation

### builder_guy
- name: '{{ users.0.name }} / Install generic config files in /home/{{ users.3.name }}/configs/'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  - roles/users/defaults/main.yml
  - roles/users/vars/main.yml

  roles:
    - configs-install


### builder_guy
- name: '{{ users.0.name }} / Test / Nginx / Generate or update .yml files and upload them'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  - roles/users/defaults/main.yml
  - roles/users/vars/main.yml

  roles:
    - stack-web-nginx-generate

### docker_guy
- name: '{{ users.2.name }} / Start tests services hello world'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    - tests-init-hello
...