---
# Use through README.md recommandations

- name: Install my web server / Generate users and set custom SSH port
  hosts: likorne
  # hosts: likorneWithCustomSSHPort
  remote_user: '{{ global__remote_user }}'
  # # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  # remote_user: '{{ users.0.name }}'
  become: yes
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml
  vars:
    currentDateTime: "{{ ansible_date_time.date }}--{{ ansible_date_time.hour }}h{{ ansible_date_time.minute }}m{{ ansible_date_time.second }}s"

  roles:
    - users
    - security-custom-ssh-port

  tasks:
    - debug:
        msg: 'You must add {{ users.0.name }} to your local SSH agent before proceeding. See generated files _{{ users.0.name }}-manual-commands-generated.md'
...