---
### Setup a WordPress stack
## builder_guy & docker_guy
# 💡How to use: Set variables in a dedicated file, duplicate this playbook (adjusting the var file) & use it

# 📌You can test this playbook by running it without modifications
# > ansible-playbook -i hostsWithCustomSSHPort 20-forge-a-wordpress-stack.yml
# It will generate & run the example sourced by the example var files
#   'roles/stack-web-wordpress--generate/vars/tests/masamune/test-wordpress--masamune--fr/test-wordpress--masamune--fr---vars.yml'
#   Files will be generated locally in 'ansible-install-web-server/ansible/generated/tests/masamune/test-wordpress--masamune--fr/'

# 🧾Step-by-step How to:
# 1. Duplicate 'ansible/roles/stack-web-wordpress--generate/vars/template.yml' to a proper location
#     like 'ansible/roles/stack-web-wordpress--generate/vars/TYPE/CLIENT/DASHED-URI/DASHED-URI---vars.yml'
# 1.1. Fill in the variables according to your needs

# 2. Duplicate this playbook file to give your project it's own playbook
#      like '200-forge---DASHED-URI---wordpress-stack.yml'
# 2.1. In your playbook file, edit the path to project variables, see the ✏️ around lines ~45 & 65

# 3. Run/Test your playbook: ~> ansible-playbook -i hostsWithCustomSSHPort 200-forge---DASHED-URI---wordpress-stack.yml
#   You can check the generated files locally in the ansible/generated/ folder

# 4. Backups if everything runs smoothly
# 4.1 Private github account, Add 20X-forge---DASHED-URI---wordpress-stack-generated.yml
# 4.1.1 History / 20X-forge---DASHED-URI---wordpress-stack-generated-{{ currentDateTime }}.yml
# 4.2 Private github account, ansible/roles/stack-web-wordpress--generate/vars/TYPE/CLIENT/DASHED-URI/DASHED-URI---vars.yml
# 4.2.1 History / ansible/roles/stack-web-wordpress--generate/vars/TYPE/CLIENT/DASHED-URI/DASHED-URI---vars-{{ currentDateTime }}.yml


# Based on bitnami's WordPress & MariaDB images
#   https://hub.docker.com/r/bitnami/wordpress/
#   https://hub.docker.com/r/bitnami/mariadb/

# You'll need the_builder_guy to have it's ssh key added to the local agent, cf. the_builder_guy generated documentation
# You'll need the_docker_guy  to have it's ssh key added to the local agent, cf. the_docker_guy  generated documentation

## builder_guy
- name: Generate or update a WordPress stack
  become: yes
  hosts: likorneWithCustomSSHPort
  # builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars:
    currentDateTime: "{{ lookup('pipe', 'date +%Y-%m-%d--%Hh%Mm%Ss') }}"
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml
  # ✏️Edit project vars files here...
  - roles/stack-web-wordpress--generate/vars/tests/masamune/test-wordpress--masamune--fr/test-wordpress--masamune--fr---vars.yml
  # - roles/stack-web-wordpress--generate/vars/tests/masamune/test-wordpress--masamune--fr/test-wordpress--masamune--fr---vars_secret.yml

  roles:
    - stack-web-wordpress--generate

# ---

## docker_guy
- name: Setup networks & volumes then start or update WordPress stack
  become: no
  hosts: likorneWithCustomSSHPort
  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml
  # ✏️... and here
  - roles/stack-web-wordpress--generate/vars/tests/masamune/test-wordpress--masamune--fr/test-wordpress--masamune--fr---vars.yml
  # - roles/stack-web-wordpress--generate/vars/tests/masamune/test-wordpress--masamune--fr/test-wordpress--masamune--fr---vars_secret.yml

  roles:
    - stack-web-wordpress--run
...