---
### Proceed to full installation with newly generated sudoer user
- name: Install my web server / Change user and SSH port then proceed
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  become: yes
  vars_files:
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    # - system-update
    - packages-installation
    # /!\ Needs a set up SSH connexion to prevent lockdown
    # See /README.md and follow steps 1 & 2 before use
    # - security
...