---
### Proceed to full installation with newly generated sudoer user
- name: 'Install my web server / Change user for {{ users.0.name }} and custom SSH port then proceed'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars_files:
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
#     - system-update
#     - packages-installation
#     - utils-time
#     - utils-terminal
#     - utils-text-editor
#     - utils-emails
#     # /!\ Needs a set up SSH connexion to prevent lockdown
#     # See /README.md and follow steps 1 & 2 before use
#     - security
#     - security-firewall
#     - security-fail2ban
    - security-apparmor
    # Install docker as root, as we will need overlay network for swarm
    #   Note: docker-compose & docker swarm will need docker installation first
    # - docker-installation
    # - docker-compose-installation
    # - docker-swarm-installation

# ### Docker manipulations
# # You'll need the_docker_guy, with proper docker management settings to execute this playbook
# # And also it's ssh key added to the local agent
# - name: 'Docker stuff / Change user for {{ users.2.name }} and then proceed'
#   become: no
#   hosts: likorneWithCustomSSHPort
#   # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
#   remote_user: '{{ users.2.name }}'
#   vars_files:
#   - roles/users/vars/main.yml

#   roles:
#     - docker-guy-check
...