---
### Proceed to full installation with newly generated sudoer user
- name: Install my web server / Change user and SSH port then proceed
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  become: yes
  vars_files:
  - roles/users/vars/main.yml

  # TODO:
  # As root
  # - Install all users, including SSH keys
  # - Change SSH port to custom
  #
  # As the builder_guy
  # - Login as the_builder_guy -p NEW_SSH_PORT
  # - All other stuff, including remove root password access

  roles:
    # - users
    - system-update
    - packages-installation
    #   # /!\ Needs a set up SSH connexion to prevent lockdown
    #   - security


...