---
### Proceed to full installation with newly generated sudoer user the_builder_guy
# You'll need it's ssh key added to the local agent, cf. the_builder_guy generated documentation
- name: 'Install my web server / {{ users.0.name }} / Utils & security setup, then docker installation & test'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    - system-update # Also upgrade to latest Ubuntu LTS
    - packages-installation
    - utils-time
    - utils-terminal
    - utils-text-editor
    - utils-emails
    # /!\ Needs a set up SSH connexion to prevent lockdown
    # See /README.md and follow steps 1 & 2 before use
    - security
    - security-firewall
    - security-fail2ban
    - security-apparmor
    - security-seccomp
    # Install docker as root, as we will need overlay network for swarm
    - docker-installation
    # Note: docker-compose & docker swarm will need docker installation first
    - docker-compose-installation
    - docker-swarm-installation
  
  tasks:
    - debug:
        msg: "\n\nAfter the docker installation, we're gonna set up the core services :\n
        - Reverse proxy (nginx)\n
        - Metrics (prometheus)\n
        - Visualizers (grafana)\n
        - Alerts (alertmanager, unsee)\n\n
        
        I'd recommand you set the following subdomains to have admin's UI :\n
        - test         .DOMAIN.COM   // Test reverse proxy through a basic website (nginx container)\n
        - prometheus   .DOMAIN.COM   // Metrics database\n
        - grafana      .DOMAIN.COM   // Visualize metrics\n
        - alertmanager .DOMAIN.COM   // Alerts dispatcher\n
        - unsee        .DOMAIN.COM   // Alert manager dashboard\n\n
        
        Example:\n
        To add the "test" subdomain to your host, you'll need the following line:\n\n

        test IN A 169.169.169.169 \n\n

        Then proceed to playbook 4 :)"
...