---
### Proceed to full installation with newly generated sudoer user the_builder_guy
# You'll need it's ssh key added to the local agent, cf. the_builder_guy generated documentation
- name: 'Install my web server / {{ users.0.name }} / Utils & security setup, then docker installation & test'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    - system-update # Also upgrade to latest Ubuntu LTS
    - packages-installation
    - utils-time
    - utils-terminal
    - utils-text-editor
    - utils-emails
    # /!\ Needs a set up SSH connexion to prevent lockdown
    # See /README.md and follow steps 1 & 2 before use
    - security
    - security-firewall
    - security-fail2ban
    - security-apparmor
    - security-seccomp
    # Install docker as root, as we will need overlay network for swarm
    - docker-installation
    # Note: docker-compose & docker swarm will need docker installation first
    - docker-compose-installation
    - docker-swarm-installation
...