---
### Docker required services setup
# Traefik       / Reverse proxy
# Test website  / Classic web serveur for test purposes
# Swarmprom     / Metrics, stats, alerts

# You'll need the_builder_guy to have it's ssh key added to the local agent, cf. the_builder_guy generated documentation
# You'll need the_docker_guy  to have it's ssh key added to the local agent, cf. the_docker_guy  generated documentation

- name: 'Docker / Remove tests artifacts and init swarm'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    # Remove tests artifacts
    - docker-maintenance
    - docker-swarm-init

# ---

# For security reasons, the_docker_peon home folder is chown to root.
# the_docker_guy permissions problems : no rights in the_docker_peon folder
# Only the builder guy can manage folders

# TODO: Comme mwa
...