---
# Use through README.md recommandations
# > ansible-playbook -i hostsWithCustomSSHPort 4-setup-core-services.yml

### Docker required services setup
# Traefik             / Reverse proxy
# Test website        / Classic web server (tutum / hello world) for test purposes
# TODO: Swarmprom     / Metrics, stats, alerts

# You'll need the_builder_guy to have it's ssh key added to the local agent, cf. the_builder_guy generated documentation
# You'll need the_docker_guy to have it's ssh key added to the local agent, cf. the_docker_guy generated documentation

### the_docker_guy
- name: 'Docker / Remove tests artifacts and init swarm'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    # Remove tests artifacts
    - docker-maintenance
    - docker-swarm-init

# ---

# For security reasons, the_docker_peon home folder is chown to root.
# the_docker_guy permissions problems : no rights in the_docker_peon folder
# Only the builder guy can manage folders

### builder_guy
- name: '{{ users.0.name }} / Core / Reverse proxy / Traefik / Generate or update service .yml files and upload them'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars:
    currentDateTime: "{{ ansible_date_time.date }}--{{ ansible_date_time.hour }}h{{ ansible_date_time.minute }}m{{ ansible_date_time.second }}s"
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  - roles/users/defaults/main.yml
  - roles/users/vars/main.yml

  roles:
    - core-reverse-proxy-traefik--generate

### docker_guy
- name: '{{ users.2.name }} / Core / Reverse proxy / Traefik / Setup networks & volumes then start or update service'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    - core-reverse-proxy-traefik--run
...