---
# Use through README.md recommandations

### Docker required services setup
# Traefik             / Reverse proxy
# Test website        / Classic web server (tutum / hello world) for test purposes
# TODO: Swarmprom     / Metrics, stats, alerts

# You'll need the_builder_guy to have it's ssh key added to the local agent, cf. the_builder_guy generated documentation
# You'll need the_docker_guy  to have it's ssh key added to the local agent, cf. the_docker_guy  generated documentation

### the_docker_guy
- name: 'Docker / Remove tests artifacts and init swarm'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    # Remove tests artifacts
    - docker-maintenance
    - docker-swarm-init

# ---

# For security reasons, the_docker_peon home folder is chown to root.
# the_docker_guy permissions problems : no rights in the_docker_peon folder
# Only the builder guy can manage folders

### builder_guy
- name: '{{ users.0.name }} / Core / Reverse proxy / Traefik / Generate or update .yml files and upload them'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars:
    currentDateTime: "{{ lookup('pipe', 'date +%Y-%m-%d--%Hh%Mm%Ss') }}"
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  - roles/users/defaults/main.yml
  - roles/users/vars/main.yml

  roles:
    - core-reverse-proxy-traefik-generate

### docker_guy
- name: '{{ users.2.name }} / Core / Reverse proxy / Traefik / Start or update service'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    - core-reverse-proxy-traefik-run



# ---



## Test core installation through a couple of hello world containers
# Currently hardcoded to serve tutum/hello (nginx) on test.masamune.fr & test-php.masamune.fr
# TODO: Add vars

### builder_guy
- name: '{{ users.0.name }} / Install generic config files in /home/{{ users.3.name }}/configs/'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  - roles/users/defaults/main.yml
  - roles/users/vars/main.yml

  roles:
    - configs-install


### builder_guy
- name: '{{ users.0.name }} / Install test services files in /home/{{ users.3.name }}/tests/'
  become: yes
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  - roles/users/defaults/main.yml
  - roles/users/vars/main.yml

  roles:
    - tests-install

### docker_guy
- name: '{{ users.2.name }} / Start tests services hello world'
  become: no
  hosts: likorneWithCustomSSHPort

  # the_docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    - tests-init-hello
...