---
### Restore a previously backuped volume: Upload a local archive to the host, then extract it into a volume
## docker_guy
# > ansible-playbook -i hostsWithCustomSSHPort 93-backup-restore-volume-from-local-archive.yml

# 🚨 Note 🚨 : This will replace existing files but **not erase new files**.
#        Best practice would be to create a new volume, populate it with the backup and remap the container accordingly.
#        This also allow the previous volume (..and datas) to persist.

# 🔧🚨💥 Variables must be properly filled:
# - archiveLocationOnHost   : The path to the folder to copy the local archive on host
# - archiveLocationOnLocal  : The path to the folder containing the archive to restore from (.tar file), locally (depending on current directory), without last slash
# - archiveName             : The archive filename to restore from (.tar file), located on host. Includes extension
# - folderToRestore         : The folder where the files are going to be restored INSIDE the volume
# - volumeName              : Identifier of the named volume to restore to a previous state

# For more details, have a look at docker-commands-template.md###Create a backup

# 📌 How to test manually:
# 1. Prepare a backup with a variation
#   1.1 Create a backup (through ansible/90-backup-volume-on-host.yml)
#   1.2 Extract it `tar -xvf test---hello--masamune--fr---nginx--logs---backup---latest.tar`
#   1.3 Edit the content `cd /FOLDER && touch hey.txt`
#   1.4 Archive it `tar -cvf updated-archive.tar "/FOLDER"`
# 2. Execute this playbook, with adjusted variables (~archiveName & archiveLocation)
# 3. Run a temporary interactive container, with mounted volume to inspect
#      docker run --rm -i -t  \
#        --mount source=VOLUME_NAME,destination=/home/whatever \
#        --userns=host \
#        -w /home/whatever \
#        alpine:latest \
#        /bin/ash
# 4. `cd` & `ls` & constat that the new file is here :)

# You'll need the_docker_guy to have it's ssh key added to the local agent, cf. the_docker_guy generated documentation

- name: 'Restore a previously backuped volume: Upload a local archive to the host, then extract it into a volume'
  become: no
  hosts: likorneWithCustomSSHPort
  # docker_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.2.name }}'
  vars:
    ## 🔧 Edit variables here
    # cf. generated .yml file > volumes > target

    # archiveLocationOnHost: '/home/{{ users.2.name }}/backups/volumes/{{ currentYear }}/imports/{{ client }}/{{ volumeName }}'
    archiveLocationOnHost: '/home/{{ users.2.name }}/backups/volumes/2021/imports/masamune/hello--masamune--fr/test---hello--masamune--fr---nginx--logs'

    # archiveLocationOnLocal: './generated/backups/volumes/{{ currentYear }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/{{ volumeName }}'
    # archiveLocationOnLocal: './generated/backups/volumes/2021/manual-backups/masamune/hello--masamune--fr/test---hello--masamune--fr---nginx--logs'
    # archiveLocationOnLocal: './generated/backups/volumes/2021/tests/masamune/hello--masamune--fr/test---hello--masamune--fr---nginx--logs'
    archiveLocationOnLocal: './generated/backups/volumes/2021/manual-backups/masamune/hello--masamune--fr/test---hello--masamune--fr---nginx--logs'
    
    # archiveName: '{{ volumeName }}---backup---latest.tar'
    archiveName: 'test---hello--masamune--fr---nginx--logs---backup---latest.tar'
    
    folderToRestore: '/var/log/'
    volumeName: 'test---hello--masamune--fr---nginx--logs'

  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml

  roles:
    - docker-volume-copy-backup-archive-to-host
    - docker-volume-restore-from-host-archive
...