---
### Removes a sftp user
# > ansible-playbook -i hostsWithCustomSSHPort 95-remove-sftp-user.yml

# 🔧 Variables should be properly filled:
# - userToRemove.name  : Id to connect (& name of the dedicated folder on the server)

# TODO: LATER: Check if user is connected (and disconnect it), else can't remove ubuntu user.

# You'll need the_builder_guy to have it's ssh key added to the local agent, cf. the_builder_guy generated documentation
# the_builder_guy
- name: Remove a stfp user
  hosts: likorneWithCustomSSHPort
  # the_builder_guy / cf. /ansible/roles/users/vars/main.yml
  remote_user: '{{ users.0.name }}'
  become: yes
  vars_files:
  - defaults/main.yml
  - roles/users/defaults/main.yml
  - vars/main.yml
  - roles/users/vars/main.yml
  vars:
    userToRemove:
      ## 🔧 Edit variables here
      name: bob
    # (Opt.) To remove README file with user instructions to setup sftp connection, in ./generated/
    project:
      type: 'test'
      client_name: 'masamune'
      dashed_domain: 'standalone-sftp-user'

  roles:
    - sftp-remove-user
...