---
- name: Install my web server / Generate users
  hosts: likorne
  remote_user: '{{ my_remote_user }}'
  become: yes
  vars_files:
  - vars/main.yml
  - roles/users/vars/main.yml

  # TODO:
  # As root
  # - Install all users, including SSH keys
  # - Change SSH port to custom
  #
  # As the builder_guy
  # - Login as the_builder_guy -p NEW_SSH_PORT
  # - All other stuff, including remove root password access

  roles:
    - users

  tasks:
    - debug:
        msg: 'You must add {{ users.0.name }} to your local SSH agent before proceeding. See generated files _{{ users.0.name }}-manual-commands-generated.md'

- name: Install my web server / Change user then proceed
  hosts: likorne
  # the_builder_guy
  remote_user: '{{ users.0.name }}'
  become: yes
  vars_files:
  - roles/users/vars/main.yml

  # TODO:
  # As root
  # - Install all users, including SSH keys
  # - Change SSH port to custom
  #
  # As the builder_guy
  # - Login as the_builder_guy -p NEW_SSH_PORT
  # - All other stuff, including remove root password access

  roles:
    # - users
    - system-update
    - packages-installation
    #   # /!\ Needs a set up SSH connexion to prevent lockdown
    #   - security


...