---
### Security

# Prevent root login (only sudoers)
- name: Prevent root login
  include: prevent-root-login.yml

# Prevent password authentication (only ssh)
- name: Prevent password authentication
  include: prevent-password-authentication.yml
...