---
### Security

# Prevent root login (only sudoers)
- name: Prevent root login
  include: prevent-root-login.yml

# Prevent password authentication (only ssh)
- name: Prevent password authentication
  include: prevent-password-authentication.yml

# Configure iptables firewall
- name: Configure iptables firewall
  include: configure-firewall.yml

# Configure fail2ban, bruteforce and spam prevention
# vars available in /ansible/roles/security/vars/main.yml
- name: Configure fail2ban, bruteforce and spam prevention
  include: configure-fail2ban.yml
...