---
### Prevent password connection (only ssh)
- name: Prevent password connexion
  lineinfile:
    # Replace line with
    line: PasswordAuthentication no
    # File to modify
    path: /etc/ssh/sshd_config
    # Attention à l'échappement
    regexp: '^PasswordAuthentication'
...