---
### Prevent password authentication (only ssh)
- name: Prevent password authentication
  lineinfile:
    # Replace line with
    line: PasswordAuthentication no
    # File to modify
    path: /etc/ssh/sshd_config
    # Attention à l'échappement
    regexp: '^PasswordAuthentication'
    # Validate sshd config file before change, # %s is mandatory for ansible but useless for this command
    validate: 'sshd -t %s'
  notify: Restart ssh service
...