---
### Prevent PAM
- name: Prevent PAM / Privileged Access Management
  lineinfile:
    # Replace line with
    line: UsePAM no
    # File to modify
    path: /etc/ssh/sshd_config
    # Attention à l'échappement
    regexp: '^UsePAM'
    # Validate sshd config file before change, # %s is mandatory for ansible but useless for this command
    validate: 'sshd -t %s'
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html
    # validate: /usr/sbin/sshd -T -f %s
  notify: Restart ssh service
...