---
### Prevent root login (only sudoers)
- name: Prevent root login
  lineinfile:
    # Replace line with
    line: PermitRootLogin no
    # File to modify
    path: /etc/ssh/sshd_config
    # Attention à l'échappement
    regexp: '^PermitRootLogin'
    # Validate sshd config file before change, # %s is mandatory for ansible but useless for this command
    validate: 'sshd -t %s'
  notify: Restart ssh service
...