---
### Prevent password authentication (only ssh)
- name: Prevent password authentication
  lineinfile:
    # Replace line with
    line: PasswordAuthentication no
    # File to modify
    path: /etc/ssh/sshd_config
    # Attention à l'échappement
    regexp: '^PasswordAuthentication'
  notify: ssh restart
...