---
### Install generic config files for nginx, using php
## the_builder_guy

# nginx w php
- name: Local / Debug / Config / Web / Nginx php / Generate './generated/configs/web/nginx/nginx-php--generated.conf'
  template:
    dest: './generated/configs/web/nginx/nginx-php--generated.conf'
    src: templates/tutum--customUser-p8080-php--nginx.conf.j2
  delegate_to: 127.0.0.1

- name: Local / History / Config / Web / Nginx php / Generate './generated/configs/web/nginx/nginx-php--generated-{{ currentDateTime }}.yml'
  template:
    dest: './generated/configs/web/nginx/nginx-php--generated-{{ currentDateTime }}.yml'
    src: templates/tutum--customUser-p8080-php--nginx.conf.j2
  delegate_to: 127.0.0.1

- debug:
    msg: "\n\nA stack file './generated/configs/web/nginx/nginx-php--generated.conf' have been generated in the /generated/ folder of this project, if you wanna make sure everything is fine :)\n"



# Install service configs file in the_docker_peon /home folder
- name: 'Create configs directory /home/{{ users.3.name }}/configs/'
  file:
    path: '/home/{{ users.3.name }}/configs/'
    state: directory


- name: Config / Web / Nginx php / Generate nginx config (custom user, internal port 8080 & php) from template
  template:
    dest: '/home/{{ users.3.name }}/configs/webserver/nginx/tutum--customUser-p8080-php--nginx.conf'
    src: templates/tutum--customUser-p8080-php--nginx.conf.j2

- name: Config / Web / Nginx php / History / Generate '/home/{{ users.3.name }}/configs/webserver/nginx/nginx--customUser-p8080--nginx-php--generated-{{ currentDateTime }}.conf'
  template:
    dest: '/home/{{ users.3.name }}/configs/webserver/nginx/nginx--customUser-p8080--nginx-php--generated-{{ currentDateTime }}.conf'
    src: templates/tutum--customUser-p8080-php--nginx.conf.j2
...