---
### WordPress ansible role generation: .yml file
## builder_guy

## This role must be run through a specific playbook.
## cf. ansible/20-forge-a-wordpress-role.yml for use case and example.

- name: Warning, without manual action this role will run an example
  debug:
    msg: "\n\nBEFORE RUNNING THIS ROLE !
          \n\nDuplicate 'ansible/roles/stack-web-wordpress--generate-role/vars/template.yml' to a proper location, ex. 'ansible/roles/stack-web-wordpress--generate/vars/TYPE/CLIENT/DASHED-DOMAIN/DASHED-DOMAIN---vars_secret.yml'
          \n\nand modify the '20-forge-a-wordpress-role.yml' playbook accordingly.\n\n"

- name: 'Read the warning message ^'
  wait_for:
    timeout: 5

- name: Generate '/200---{{ project.dashed_domain }}---forge-wordpress-stack--generated.yml'
  delegate_to: 127.0.0.1
  template:
    dest: './200---{{ project.dashed_domain }}---forge-wordpress-stack--generated.yml'
    src: wordpress-role.yml.j2

- name: Create directory './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/roles/'
  delegate_to: 127.0.0.1
  file:
    path: './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/roles/'
    state: directory

- name: History / Generate './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/roles/200---{{ project.dashed_domain }}---forge-wordpress-stack--generated-{{ currentDateTime }}.yml'
  delegate_to: 127.0.0.1
  template:
    dest: './generated/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/roles/200---{{ project.dashed_domain }}---forge-wordpress-stack--generated-{{ currentDateTime }}.yml'
    src: wordpress-role.yml.j2
...