---
### Apply recommanded Docker Security Cheat Sheet stuff
#   https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Docker_Security_Cheat_Sheet.md

## RULE #0 - Keep Host and Docker up to date
# ok

## RULE #1 - Do not expose the Docker daemon socket (even to the containers)
# I'll have to for traefik, but i'll use a proxy container

## RULE #2 - Set a user
# Remote user created (the_docker_peon),
# TODO: Need to force it inside containers during creation...

## RULE #3 - Limit capabilities (Grant only specific capabilities, needed by a container)
# Can't set default drop all capabilites to docker containers.
# TODO: Need to create profiles

## RULE #4 - Add –no-new-privileges flag
# TODO: Need to create profiles

## RULE #5 - Disable inter-container communication (--icc=false)
# Edited in docker daemon config file

## RULE #6 - Use Linux Security Module (seccomp, AppArmor, or SELinux)
# Need to create AppArmor profiles, load them and force them

## RULE #7 - Limit resources (memory, CPU, file descriptors, processes, restarts)
# I plan to use only services, and fine tune the resources allocation after installing the metrics
# Can also set default limits through docker daemon config
#   https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit
#     https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
#     https://docs.oracle.com/en/operating-systems/oracle-linux/docker/ch04s16.html
# Edited in docker daemon config file
#   > Docker default 64000, drastically reduced.
#   > This example sets a soft limit of 128 open files and 32 child processes and a hard limit of 256 open files and 64 child processes on the container.

## RULE #8 - Set filesystem and volumes to read-only
# TODO: Need to create profiles

## RULE #9 - Use static analysis tools
# TODO: Later

## RULE #10 - Set the logging level to at least INFO
# Edited in docker daemon config file
...