---
### Apply recommanded post installation steps
#   https://docs.docker.com/install/linux/linux-postinstall/

# To keep the cookbook concise, please refer to
# - /ansible/roles/docker-installation/templates/etc-docker-daemon-json.md    for detailed explanations
# - /ansible/roles/docker-installation/templates/etc-docker-daemon-json.j2    for the generated daemon.json file


## Manage Docker as a non-root user
#   https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
# Already done during user creation, cf. /ansible/roles/users/tasks/main.yml
# - Creating 'docker' group
# - Add the_docker_guy to the 'docker' group
# This user is used after docker installation and configuration

## Configure Docker to start on boot
#   https://docs.docker.com/install/linux/linux-postinstall/#configure-docker-to-start-on-boot
# Already done during docker installation through 'enabled: true'

## Use a different storage engine
#   https://docs.docker.com/install/linux/linux-postinstall/#use-a-different-storage-engine
# Default (overlay2) for ubuntu:18.04 is recommanded / https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-engine---community
# TODO: check this stuff in details

## Configure default logging driver
#   https://docs.docker.com/install/linux/linux-postinstall/#configure-default-logging-driver
#   DEPRECATED: After some researchs, default 'json-file' seems recommanded for ubuntu:18.04
#   Docker bench security recommands syslog.
# Explicitly specify the logging driver & configure it to prevent massive logs files
#   cf. daemon.json

# TODO: Check compatibility with Swarmprom monitoring
# TODO: Find an UI to display logs, cf. ~datadog, if it doesn't already exist in grafana/plugins

## Configure where the Docker daemon listens for connections
#   https://docs.docker.com/install/linux/linux-postinstall/#configure-where-the-docker-daemon-listens-for-connections
# aka. remote access to docker daemon
#   Won't be needed as mot things will run through ssh ansible

# Other steps concern troubleshooting and won't be handled here

# ---

## Your kernel does not support cgroup swap limit capabilities
#     https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
- name: 'Enable cgroup swap limit capabilities : Edit grub'
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
  # 📌 Reboot needs to occur after grub update v
  notify: Reboot the Debian or Ubuntu server

- name: 'Enable cgroup swap limit capabilities : update grub'
  # Needs sudo
  ansible.builtin.shell: update-grub
...