---
## the_builder_guy
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/stack/'
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history/stack/'

- name: Generate nginx.conf
  template:
    dest: '{{ item }}'
    src: templates/nginx.conf.j2
  loop:
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/stack/{{ project.dashed_domain }}---nginx--generated.conf'
    - '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/history/stack/{{ project.dashed_domain }}---nginx--generated-{{ currentDateTime }}.conf'

- debug:
    msg:
      - "A stack file '{{ root_folder }}/{{ project.type }}s/{{ project.client_name }}/{{ project.dashed_domain }}/stack/{{ project.dashed_domain }}---nginx--generated.conf' have been generated in the {{ root_folder }} folder of this project,"
      - "if you wanna make sure everything is fine :)"
  when: root_folder == './generated'
...